[pytest]
DJANGO_SETTINGS_MODULE = config.settings
testpaths = mis users
python_files = test_*.py tests.py
addopts = --cov=mis --cov=users --cov-report=html
norecursedirs = .git .venv venv env build dist *.egg-info **/migrations __pycache__ .pytest_cache

[coverage:run]
omit =
    mis/migrations/*
    users/migrations/*
    */site-packages/*