# Generated by Django 6.0.3 on 2026-03-22 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InformationSystem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите наименование ИС", max_length=150, verbose_name="Наименование ИС"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите пользователя - владельца ИС",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_is",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информационная система",
                "verbose_name_plural": "Информационные системы",
                "ordering": ["title"],
            },
        ),
    ]
