# Generated by Django 6.0.3 on 2026-03-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformationSystemRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите наименование роли в ИС",
                        max_length=150,
                        verbose_name="Наименование роли в ИС",
                    ),
                ),
                (
                    "information_system",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите наименование ИС",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_is",
                        to="mis.informationsystem",
                        verbose_name="Наименование ИС",
                    ),
                ),
            ],
        ),
    ]
