# Generated by Django 6.0.3 on 2026-03-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0002_informationsystemrole"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="informationsystemrole",
            options={
                "ordering": ["title"],
                "verbose_name": "Роль информационной системы",
                "verbose_name_plural": "Роли информационных систем",
            },
        ),
    ]
