# Generated by Django 6.0.3 on 2026-03-22 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0003_alter_informationsystemrole_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, help_text="Укажите дату создания", verbose_name="Дата создания"
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[("READ", "Чтение"), ("WRITE", "Запись")],
                        default="READ",
                        editable=False,
                        help_text="Укажите уровень доступа",
                        max_length=10,
                        verbose_name="Уровень доступа",
                    ),
                ),
                (
                    "approved_status_supervisor_is",
                    models.CharField(
                        choices=[
                            ("pending", "На согласовании"),
                            ("approved", "Согласовано"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        editable=False,
                        help_text="Укажите статус согласования непосредственным руководителем",
                        max_length=20,
                        verbose_name="Статус согласования непосредственным руководителем",
                    ),
                ),
                (
                    "approved_status_owner_is",
                    models.CharField(
                        choices=[
                            ("pending", "На согласовании"),
                            ("approved", "Согласовано"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        editable=False,
                        help_text="Укажите статус согласования владельцем ИС",
                        max_length=20,
                        verbose_name="Статус согласования владельцем ИС",
                    ),
                ),
                (
                    "approved_status_ib_is",
                    models.CharField(
                        choices=[
                            ("pending", "На согласовании"),
                            ("approved", "Согласовано"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        editable=False,
                        help_text="Укажите статус согласования сотрудником ИБ",
                        max_length=20,
                        verbose_name="Статус согласования сотрудником ИБ",
                    ),
                ),
                (
                    "information_system",
                    models.ForeignKey(
                        help_text="Укажите наименование ИС",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_request_is",
                        to="mis.informationsystem",
                        verbose_name="Наименование ИС",
                    ),
                ),
                (
                    "information_system_role",
                    models.ForeignKey(
                        help_text="Укажите наименование роли в ИС",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_request_isr",
                        to="mis.informationsystemrole",
                        verbose_name="Наименование роли в ИС",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите пользователя - подающего заявку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_access_request",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите непосредственного руководителя",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisor_access_request",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Непосредственный руководитель",
                    ),
                ),
            ],
        ),
    ]
