# Generated by Django 6.0.3 on 2026-03-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0004_accessrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessrequest",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Заявка на доступ к ИС",
                "verbose_name_plural": "Заявки на доступ к ИС",
            },
        ),
    ]
