# Generated by Django 6.0.3 on 2026-03-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0005_alter_accessrequest_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="informationsystemrole",
            options={
                "ordering": ["information_system", "title"],
                "verbose_name": "Роль информационной системы",
                "verbose_name_plural": "Роли информационных систем",
            },
        ),
    ]
