# Generated by Django 6.0.3 on 2026-03-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0006_alter_informationsystemrole_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="permission_level",
            field=models.CharField(
                choices=[("READ", "Чтение"), ("WRITE", "Запись")],
                default="READ",
                help_text="Укажите уровень доступа",
                max_length=10,
                verbose_name="Уровень доступа",
            ),
        ),
    ]
