# Generated by Django 6.0.3 on 2026-03-22 14:36

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0007_alter_accessrequest_permission_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="information_system_role",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="information_system",
                chained_model_field="information_system",
                help_text="Укажите наименование роли в ИС",
                on_delete=django.db.models.deletion.CASCADE,
                to="mis.informationsystemrole",
                verbose_name="Наименование роли в ИС",
            ),
        ),
    ]
