# Generated by Django 6.0.3 on 2026-03-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0008_alter_accessrequest_information_system_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessrequest",
            options={
                "ordering": ["created_at"],
                "permissions": [
                    ("can_status_supervisor", "Может согласовывать как руководитель"),
                    ("can_status_owner_is", "Может согласовывать как владелец ИС"),
                    ("can_status_ib", "Может согласовывать как сотрудник ИБ"),
                ],
                "verbose_name": "Заявка на доступ к ИС",
                "verbose_name_plural": "Заявки на доступ к ИС",
            },
        ),
    ]
