# Generated by Django 6.0.3 on 2026-03-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0009_alter_accessrequest_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="supervisor",
            field=models.ForeignKey(
                help_text="Укажите непосредственного руководителя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisor_access_request",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Непосредственный руководитель",
            ),
        ),
    ]
