# Generated by Django 6.0.3 on 2026-03-28 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mis", "0010_alter_accessrequest_supervisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationsystem",
            name="owner",
            field=models.ForeignKey(
                help_text="Укажите пользователя - владельца ИС",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_is",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
